#!/bin/bash

hello_world() {
	echo "Hello World"
	
}

hello_world

printf "Give me a number: "
read userNum
echo "User num is $userNum"
echo 'User num is $userNum'

file_count=$(ls | wc -l)
file_count=`ls | wc -l`

echo "File count in current dir is $file_count"

for i in {0..100..5}
do
	printf "$i "
done

echo

for element in Hydrogen Helium Lithium Beryllium
do
  echo "Element: $element"
done

i=0

while [ $i -le 2 ]
do
  echo "Number: $i"
  ((i++))
done


file=/etc/passwd
#file=

#while IFS= read -r line; do
#  echo $line
#done < "$file"






