title: CEG 2350
#logo: assets/images/kastle-gradient.png
description: Operating Systems Concepts & Design
show_downloads: false

remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
    - jekyll-remote-theme
